steps:
  - id: build-and-push-app-images
    name: gcr.io/cloud-builders/docker
    dir: cloud_run_builder
    entrypoint: bash
    args: ["./scripts/build.sh"]
    env:
      - "PROJECT_ID=$PROJECT_ID"
      - "BRANCH_NAME=$BRANCH_NAME"
      - "SHORT_SHA=$SHORT_SHA"
      - "BUILD_ID=$BUILD_ID"
      - "DEPLOY_REGION=$_REGION"
      - "AR_REPOSITORY=$_AR_REPOSITORY"

  - id: deploy-apps-to-cloud-run
    name: gcr.io/google.com/cloudsdktool/google-cloud-cli:stable
    dir: cloud_run_builder
    entrypoint: bash
    args: ["./scripts/deploy.sh"]
    env:
      - "PROJECT_ID=$PROJECT_ID"
      - "BRANCH_NAME=$BRANCH_NAME"
      - "SHORT_SHA=$SHORT_SHA"
      - "BUILD_ID=$BUILD_ID"
      - "DEPLOY_REGION=$_REGION"
      - "AR_REPOSITORY=$_AR_REPOSITORY"

substitutions:
  _REGION: us-central1
  _AR_REPOSITORY: cloud-run

options:
  logging: CLOUD_LOGGING_ONLY