
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.
# Application Template: projects/default-project/locations/us-central1/spaces/default-space/applicationTemplates/default-app-template

module "bigquery-dataset" {
  source     = "github.com/terraform-google-modules/terraform-google-bigquery?ref=v10.2.1"
  dataset_id = var.bigquery-dataset_dataset_id
  location   = var.bigquery-dataset_location
  project_id = var.bigquery-dataset_project_id
  tables = [
    {
      schema   = "[{\"description\": \"A string type unique identifier\",\"mode\": \"NULLABLE\",\"name\": \"simpleId\",\"type\": \"STRING\"},{\"description\": \"A field to hold integer values\",\"mode\": \"NULLABLE\",\"name\": \"integerField\",\"type\": \"INTEGER\"},{\"description\": \"Data\",\"mode\": \"NULLABLE\",\"name\": \"data\",\"type\": \"STRING\"}]"
      table_id = "table-1"
    },
  ]
}
module "export-bucket" {
  source     = "github.com/terraform-google-modules/terraform-google-cloud-storage//modules/simple_bucket?ref=v12.3.0"
  project_id = var.export-bucket_project_id
  location   = var.export-bucket_location
  name       = var.export-bucket_name
  iam_members = [
    {
      member = module.export-service.service_account_id.member
      role   = "roles/storage.objectAdmin"
    },
  ]
  storage_class = "STANDARD"
}
module "export-service" {
  source       = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.33.0"
  project_id   = var.export-service_project_id
  location     = var.export-service_location
  service_name = var.export-service_service_name
  containers = [
    {
      container_image = "us-docker.pkg.dev/cloudrun/container/hello"
      container_name  = "service-container"
      env_vars = {
        bigquery_dataset_BIGQUERY_DATASET            = module.bigquery-dataset.env_vars.BIGQUERY_DATASET
        bigquery_dataset_BIGQUERY_EXTERNAL_TABLES    = module.bigquery-dataset.env_vars.BIGQUERY_EXTERNAL_TABLES
        bigquery_dataset_BIGQUERY_MATERIALIZED_VIEWS = module.bigquery-dataset.env_vars.BIGQUERY_MATERIALIZED_VIEWS
        bigquery_dataset_BIGQUERY_ROUTINES           = module.bigquery-dataset.env_vars.BIGQUERY_ROUTINES
        bigquery_dataset_BIGQUERY_TABLES             = module.bigquery-dataset.env_vars.BIGQUERY_TABLES
        bigquery_dataset_BIGQUERY_VIEWS              = module.bigquery-dataset.env_vars.BIGQUERY_VIEWS
      }
      ports = {
        container_port = 8080
      }
      volume_mounts = [{
        mount_path = "/gcs-bucket-vol"
        name       = "gcs-bucket-vol"
      }]
    },
  ]
  gpu_zonal_redundancy_disabled = false
  service_account_project_roles = [
    "roles/bigquery.dataEditor",
  ]
  vpc_access = {
    egress = "PRIVATE_RANGES_ONLY"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  volumes = [
    {
      gcs = {
        bucket = module.export-bucket.name
      }
      name = "gcs-bucket-vol"
    },
  ]
  service_scaling = {
    min_instance_count = 0
  }
  template_scaling = {
    min_instance_count = 0
  }
}
