
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.
# Application Template: projects/default-project/locations/us-central1/spaces/default-space/applicationTemplates/default-app-template

output "export-service_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.export-service.service_uri
}
