
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.
# Application Template: projects/default-project/locations/us-central1/spaces/default-space/applicationTemplates/default-app-template

bigquery-dataset_dataset_id = "export_dataset"
bigquery-dataset_project_id = "jag-data-hub-01"
export-bucket_project_id    = "jag-data-hub-01"
export-bucket_location      = "us-central1"
export-bucket_name          = "jag-data-hub-01-export-bucket"
export-service_project_id   = "jag-data-hub-01"
export-service_location     = "us-central1"
export-service_service_name = "export-service"
