
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.
# Application Template: projects/default-project/locations/us-central1/spaces/default-space/applicationTemplates/default-app-template

variable "bigquery-dataset_dataset_id" {
  description = "Unique ID for the dataset being provisioned."
  type = string
}
variable "bigquery-dataset_location" {
  description = "The location of the dataset. For multi-region, US or EU can be provided."
  default     = "US"
  type = string
}
variable "bigquery-dataset_project_id" {
  description = "Project where the dataset and table are created"
  type = string
}
variable "export-bucket_project_id" {
  description = "The ID of the project to create the bucket in."
  type = string
}
variable "export-bucket_location" {
  description = "The location of the bucket. See https://cloud.google.com/storage/docs/locations."
  type = string
}
variable "export-bucket_name" {
  description = "The name of the bucket."
  type = string
}
variable "export-service_project_id" {
  description = "The project ID to deploy to"
  type = string
}
variable "export-service_location" {
  description = "Cloud Run service deployment location"
  type = string
}
variable "export-service_service_name" {
  description = "The name of the Cloud Run service to create"
  type = string
}
